from __future__ import annotations

import hashlib
import os
from datetime import datetime, timezone
from html import escape
from typing import Any

import requests

from insta_newsletter import generate_newsletter

READWISE_SAVE_URL = "https://readwise.io/api/v3/save/"
DEFAULT_TAGS = ["instagram", "newsletter"]


def _build_document_url(newsletter_text: str) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    digest = hashlib.sha256(newsletter_text.encode("utf-8")).hexdigest()[:12]
    return f"https://insta-newsletter.local/{today}/{digest}"


def _build_newsletter_html(newsletter_text: str, title: str) -> str:
    safe_title = escape(title)
    safe_body = escape(newsletter_text)
    return (
        f"<article><h1>{safe_title}</h1>"
        f"<pre style='white-space: pre-wrap; font-family: system-ui;'>{safe_body}</pre>"
        "</article>"
    )


def send_newsletter_to_readwise(
    newsletter_text: str,
    *,
    access_token: str | None = None,
    title: str | None = None,
    tags: list[str] | None = None,
    notes: str | None = None,
    timeout: int = 30,
) -> dict[str, Any]:
    if not newsletter_text.strip():
        raise ValueError("newsletter_text must not be empty")

    token = access_token or os.getenv("READWISE_ACCESS_TOKEN")
    if not token:
        raise ValueError("Missing Readwise token. Set READWISE_ACCESS_TOKEN.")

    doc_title = title or f"Instagram Newsletter ({datetime.now().date().isoformat()})"
    payload: dict[str, Any] = {
        "url": _build_document_url(newsletter_text),
        "html": _build_newsletter_html(newsletter_text, doc_title),
        "category": "note",
        "saved_using": "insta-newsletter",
        "tags": tags or DEFAULT_TAGS,
    }
    if notes:
        payload["notes"] = notes

    response = requests.post(
        READWISE_SAVE_URL,
        headers={"Authorization": f"Token {token}"},
        json=payload,
        timeout=timeout,
    )
    response.raise_for_status()
    return response.json()


def run_newsletter_to_readwise() -> int:
    token = os.getenv("READWISE_ACCESS_TOKEN")
    if not token:
        print(
            "Readwise wrapper failed: missing READWISE_ACCESS_TOKEN environment variable. "
            "Set it before running send_readwise_insta_newsletter.py (example: "
            "export READWISE_ACCESS_TOKEN=\"your_readwise_access_token\").",
        )
        return 1

    try:
        summary, elapsed, accounts_checked, accounts_with_posts = generate_newsletter()
        result = send_newsletter_to_readwise(
            summary,
            access_token=token,
            notes=f"Generated by insta-newsletter in {elapsed:.2f} seconds.",
        )
    except Exception as e:
        print(f"Readwise wrapper failed: {e}")
        if "Multiple authentication errors detected while contacting Instagram" in str(e):
            print("Newsletter was not sent to Readwise due to Instagram authentication errors.")
        return 1

    print(summary)
    print("\n---")
    print(f" Generated in {elapsed:.2f} seconds")
    print(f" Accounts checked: {accounts_checked}")
    print(f" Accounts with recent posts: {accounts_with_posts}")
    print(f" Sent to Readwise feed (id={result.get('id', 'unknown')})")
    return 0


if __name__ == "__main__":
    raise SystemExit(run_newsletter_to_readwise())
